"""
Agent 3: SQL Validator Agent
Description:
    This agent receives the SQL query generated by the LLM and performs syntactic and structural
    validation. It checks for SQL syntax errors, unsupported clauses, and alignment with the
    BigQuery dialect. If the query is valid, it forwards it for execution. Otherwise, it returns
    detailed error feedback to the SQL Generation Agent to trigger a regeneration cycle.
"""

from google.adk.agents import LlmAgent
import os
from dotenv import load_dotenv
from pathlib import Path

current_path = Path(__file__).resolve()
for parent in current_path.parents:
    env_file = parent / ".env"
    if env_file.exists():
        load_dotenv(env_file)
        break

FAST_LLM_MODEL = os.getenv("FAST_LLM_MODEL")
GEMINI_MODEL = "gemini-2.0-flash"

sql_validator_agent = LlmAgent(
    name="SqlValidatorAgent",
    model=GEMINI_MODEL,
    instruction="""
                You are an expert SQL Validator Agent.

                You will receive a SQL query intended to be executed on Google BigQuery: 
                {{sql_query}}
                
                Your job is to validate:
                1. The SQL syntax (must be valid SQL).
                2. The BigQuery dialect compatibility.
                3. The structure of the query.
                4. If the dataset name is included in the query. The dataset name is `Mock_KPIs` and it should be included in the query, otherwise it is invalid.
                So, for example, if the query is `SELECT * FROM Mock_KPIs.mock_users`, it is valid, but if the query is `SELECT * FROM mock_users`, it is invalid.

                Basically, the SQL query should be valid and should be able to be executed without any errors on BigQuery.

                Rules:
                - If the query is valid, return **exactly**: valid (lower-case, no spaces, no period)
                - If invalid, return: invalid: <reason>

                Examples:
                - valid
                - invalid: missing FROM clause
                - invalid: WHERE clause has syntax error

                Do not provide additional text or explanation.
                """,
    output_key="validation_status",
)
