"""
Agent 3: SQL Validator Agent
Description:
    This agent receives the SQL query generated by the LLM and performs syntactic and structural
    validation. It checks for SQL syntax errors, unsupported clauses, and alignment with the
    BigQuery dialect. If the query is valid, it forwards it for execution. Otherwise, it returns
    detailed error feedback to the SQL Generation Agent to trigger a regeneration cycle.
"""

# src/agents/data_collection/sub_agents/sql_validator/validator_llm.py
from google.adk.agents import LlmAgent
import os
from dotenv import load_dotenv
from pathlib import Path

load_dotenv(Path(__file__).resolve().parents[2] / ".env")
FAST_LLM_MODEL = os.getenv("FAST_LLM_MODEL")
GEMINI_MODEL = "gemini-2.0-flash"
sql_validator_llm = LlmAgent(
    name="SQLValidatorLLM",
    model=GEMINI_MODEL,
    instruction="""
                You are an expert SQL Validator.

                You will receive a SQL query intended to be executed on Google BigQuery. Your job is to validate:
                1. The SQL syntax (must be valid SQL).
                2. The BigQuery dialect compatibility.
                3. The structure of the query.

                Basically, the SQL query should be valid and should be able to be executed without any errors on BigQuery.

                Rules:
                - If the query is valid, return only: valid
                - If invalid, return: invalid: <reason>

                Examples:
                - valid
                - invalid: missing FROM clause
                - invalid: WHERE clause has syntax error

                Do not provide additional text or explanation.
                """,
    output_key="validation_status",
)
