"""
Agent 3: SQL Validator Agent
Description:
    This agent receives the SQL query generated by the LLM and performs syntactic and structural
    validation. It checks for SQL syntax errors, unsupported clauses, and alignment with the
    BigQuery dialect. If the query is valid, it forwards it for execution. Otherwise, it returns
    detailed error feedback to the SQL Generation Agent to trigger a regeneration cycle.
"""